
# OS detected
ifeq ($(OS),Windows_NT)
	ifneq ($(findstring .exe,$(SHELL)),)
    OS_TYPE := Windows
	else
    OS_TYPE := Cygwin
	endif
else
    OS_TYPE := $(shell uname -s)
endif

# Program Defintions
TEX    = lualatex -shell-escape -8bit 
BIBTEX = bibtex
INDEX  = makeindex -q 
RM     = $(if $(filter $(OS_TYPE),Windows),del /f /q ,rm -f )

all:class doc example

unpack:hustbeamer.dtx hustbeamer.ins
	@$(TEX) hustbeamer.ins

%.cls %.tex %.md %.bib:hustbeamer.dtx hustbeamer.ins
	@$(TEX) hustbeamer.ins

class:hustbeamer.cls

doc:hustbeamer.pdf

hustbeamer.pdf:hustbeamer.dtx
	@$(TEX) $(^F)
	@$(INDEX) -s l3doc.ist $(basename $(^F))
	@$(TEX) $(^F)
	@$(TEX) $(^F)

example:hustbeamer-example.pdf

hustbeamer-example.pdf:hustbeamer-example.tex hustbeamer.cls
	@$(TEX) $(<F)
	@$(TEX) $(<F)

clean:
	-$(RM) *.acn *.acr *.alg *.aux *.bbl \
			*.blg *.dvi *.fdb_latexmk *.glg *.glo \
			*.gls *.idx *.ilg *.hd *.ind *.ist \
			*.lof *.log *.lot *.maf *.mtc \
			*.mtc0 *.nav *.nlo *.out *.pdfsync \
			*.pyg *.snm *.synctex.gz *.thm *.toc \
			*.vrb *.xdy *.tdo \
			*.cls *.tex *.md *.bib

reallyclean:
	-$(RM) *.acn *.acr *.alg *.aux *.bbl \
			*.blg *.dvi *.fdb_latexmk *.glg *.glo \
			*.gls *.idx *.ilg *.hd *.ind *.ist \
			*.lof *.log *.lot *.maf *.mtc \
			*.mtc0 *.nav *.nlo *.out *.pdfsync \
			*.pyg *.snm *.synctex.gz *.thm *.toc \
			*.vrb *.xdy *.tdo \
			*.cls *.tex *.md *.bib hustbeamer*.pdf

checksum:FORCE
	perl adjust_checksum.pl hustbeamer.dtx

.PHONY:all unpack class doc example clean reallyclean checksum FORCE
